Repository fes300/ts-endpoint, pull requests merged in 2021-01, with the labels that each got.

#59 fix: endpoint body type inference
  packages/ts-endpoint-express/src/__typetests__/__snapshots__/addEndpoint.typespec.ts.snap
  packages/ts-endpoint-express/src/__typetests__/addEndpoint.typespec.ts
  packages/ts-endpoint-express/src/index.ts
  packages/ts-endpoint/src/Endpoint/Endpoint.ts
  packages/ts-endpoint/src/Endpoint/withAuth.ts
Labels: bug

#60 fix: pass error to next express handler
  packages/ts-endpoint-express/src/index.ts
Labels: refactor

#65 feat: small improvements
  packages/ts-endpoint-browser/src/__test__/fetch.spec.ts
  packages/ts-endpoint-browser/src/__typetests__/fetch.typespec.ts
  packages/ts-endpoint-browser/src/fetch.ts
  packages/ts-endpoint-browser/src/index.ts
  packages/ts-endpoint-browser/src/swr.ts
  packages/ts-endpoint/src/Endpoint/Endpoint.ts
Labels: enhancement
